<?php
/**
 * Created by EzrealRao MacBook
 * User: Ezreal Rao
 * Date: 2019/12/9
 * Time: 16:52
 */

declare(strict_types = 1);

return [
    "resource_not_found"                 => "资源未找到",
    "unauthorized"                       => "未授权",
    "account_cancelled"                  => "账号已注销",
    "token_authentication_does_not_pass" => "Token验证失败",
    "internal_server_error"              => "服务器内部错误",
    "unknown_error"                      => "未知错误",
    "parameter_error"                    => "参数错误",
    "system_busy"                        => "系统繁忙，请稍后重试",
    "orders"                             => [
        "address_error"                 => "地址不存在",
        "shop_not_found"                => "店铺不存在",
        "products_not_found"            => "商品不存在",
        "not_found_or_status_wrong"     => "该订单找不到或者状态不正确",
        "repeat_evaluation"             => "不能重复评价",
        "warehouse_error"               => "请填写仓库地址",
        "address_not_found"             => "收货地址不存在",
        "delivery_not_supported"        => "物流不支持该区域",
        "weight_not_supported"          => "该订单重量不支持快递",
        "pay_amount_can_not_order"      => "支付金额不允许下单",
        "weight_not_supported_delivery" => "该订单重量不支持快递",
        "logistics_stop"                => "春节期间快递即日起停运至2月1日恢复",
    ],
    "auth"                               => [
        "mobile_is_invalid" => "手机号 必须是一个有效的电话号码",
    ],
    "login" => [
        "login_failed"            => "登录失败",
        "unknown_error"           => "未知错误",
        "system_busy"             => "系统繁忙请重试",
        "logout_failed"           => "退出失败",
        "token_not_found"         => "token不能为空",
        "wx_login_except"         => "微信登录异常，请稍后再试",
        "wx_authorization_failed" => "微信授权失败，请稍后再试",
        "wx_account_bind_repeat"  => "该账号已绑定微信，请勿重复绑定",
        "wx_union_id_bind_repeat" => "该微信已绑定在其他账号，请解绑后再进行此操作",
    ],
    "bank_card_frozen" => [
        "card_already_exists"         => "该银行账户已经存在申请记录",
        "invalid_credit_code"         => "无效的统一社会信用代码",
        "credit_code_not_belong_yiwu" => "非义乌地区统一社会信用代码",
        "store_failed"                => "登记失败，请稍后再试",
    ],
    "user"                               => [
        "name"                        => "名称",
        "avatar"                      => "头像",
        "un_certified"                => "请认证后再注册",
        "user_type_mismatch"          => "认证类型不匹配",
        "best_sign_register_failed"   => "合同注册失败",
        "authentication_not_found"    => "用户认证信息不存在",
        "at_least_one_phone_or_email" => "手机号与email必须存在一个",
        "invalid_login_grant"         => "无效的登录模式",
    ],
    "products"                           => [
        "not_found"                   => "产品不存在",
        "shortages_stock"             => "库存不足",
        "privates_password"           => "密码错误",
        "evaluations_list_get_failed" => "评价列表获取失败",
    ],
    "shops"                              => [
        "shop_not_found"          => "店铺不存在",
        "register_advisory_error" => "注册咨询异常",
        "id_card_is_invalid"      => "证件号码无效",
    ],
    "coupon"                             => [
        "already_receive"        => "您已经领取过该优惠券",
        "not_found"              => "该优惠券不存在",
        "already_receive_finish" => "该优惠券已被领取完",
        "not_be_used"            => "该优惠券现在还不能使用",
        "expired"                => "该优惠券已过期",
    ],
    "upload"                             => [
        "failed" => "上传失败",
        "file"   => "文件无效",
        "image"  => "图片格式不正确",
        "limit"  => "上传文件个数已达上限",
    ],
    "refund"                             => [
        "status_error"          => "订单状态不支持退货退款",
        "account_error"         => "订单实付金额不支持退货退款",
        "pay_method_error"      => "订单支付方式不支持退货退款",
        "not_found"             => "不存在可退款退货订单",
        "product_not_found"     => "退货的产品不存在",
        "quantity_too_much"     => "退货数量超过购买数量",
        "product_cannot_refund" => "部分产品购买价格过低不支持退货",
        "result_error"          => "退款失败，请稍后再试",
        "refund_amount_less"    => "产品退款金额少于0.01",
        "pay_way_error"         => "该笔订单支付路径暂不支持退款",
    ],
    "evaluation"                         => [
        "not_found"                           => "未找到该订单或状态不正确",
        "repeat_evaluation"                   => "不能重复评价",
        "pay_method_not_supported_evaluation" => "该订单不支持评价",
    ],
    "logistics"                          => [
        "query_failed" => "物流信息查询失败",
    ],
    "cart"                               => [
        "parameter_error"         => "参数错误",
        "product_not_exists"      => "产品不存在",
        "out_of_stock"            => "库存不足",
        "in_stock"                => "有货",
        "no_stock"                => "无货",
        "update_error"            => "购物车更新失败",
        "add_error"               => "加入购物车失败",
        "deleted_error"           => "删除失败",
        "upload_product_not_exit" => "更新的产品不存在",
        "select_attr_error"       => "商品属性选择错误",
        "quantity_limit"          => "超过数量限制",
        "quantity_not_allow"      => "商品数量不允许加购",
        "cart_limit"              => "超过购物车上限",
    ],
    "live"                               => [
        "not_found"         => "暂无直播",
        "list_get_failed"   => "直播列表获取失败",
        "detail_get_failed" => "直播详情获取失败",
        "add_like_number"   => "直播点赞失败",
        "center_get_failed" => "直播C位获取失败",
    ],
    "address"                            => [
        "add_failed"         => "收货地址新增失败",
        "edit_failed"        => "收货地址编辑失败",
        "del_failed"         => "收货地址删除失败",
        "not_found"          => "收货地址不存在",
        "default_set_failed" => "默认地址设置失败",
    ],
    "collection"                         => [
        "repeat"            => "请不要重复收藏",
        "create_failed"     => "收藏失败，请稍后再试",
        "delete_failed"     => "取消收藏失败，请稍后再试",
        "shop_not_found"    => "店铺不存在",
        "product_not_found" => "商品不存在",
    ],
    "notify"                             => [
        "mark_failed"        => "已读标记失败",
        "del_failed"         => "删除失败",
        "not_found_can_read" => "暂无可标记消息",
    ],
    "order"                              => [
        "product_or_quantity_error"   => "产品或者数量错误",
        "product_not_in_cart"         => "购物车中不存在该商品",
        "product_not_exist"           => "商品不存在",
        "product_under_stock"         => "商品库存不足",
        "params_error"                => "参数错误",
        "product_quantity_error"      => "商品数量错误",
        "contract_not_allow"          => "选中的商品无法使用合同下单",
        "product_amount_error"        => "订单金额不支持下单",
        "Order_Generation_Failed"     => "订单生成失败",
        "not_support_multi_shop"      => "暂不支持多店铺下单",
        "cancel_error"                => "取消失败",
        "destroy_error"               => "删除失败",
        "order_not_exists"            => "订单不存在",
        "not_to_sign"                 => "订单无需签约",
        "wait_merchant_sign"          => "合同等待商家签订中.",
        "user_not_auth"               => "用户未认证，无法下单",
        "sign_addr_fail"              => "获取签约地址失败",
        "status_not_can_pay"          => "订单状态不可支付",
        "amount_can_pay"              => "金额不足0.01，不可支付",
        "receive_error"               => "确认收货失败",
        "eva_error"                   => "评价失败",
        "order_payment_num"           => "支付单号",
        "not_pay"                     => "未支付",
        "contract_error"              => "签约失败",
        "contract_not_exists"         => "合同不存在",
        "sign_not_auth"               => "未在上上签处实名",
        "product_can_not_buy"         => "当前产品不可买",
        "shop_can_not_pay"            => "抱歉，该店铺尚未开通支付功能",
        "not_support_multi_currency"  => "不支持多种币种",
        "shop_can_not_pay_foreign"    => "店铺当前不支持外汇支付",
        "order_not_settle"            => "订单结算失败",
        "express_error"               => "查询无结果，请隔段时间再查",
        "order_receive_error"         => "确认收货必须晚于支付时间24小时",
        "order_not_refund"            => "订单退款失败",
        "product_effective"           => "商品已经失效",
        "coupon_can_not_used"         => "该交易方式不能使用优惠券",
        "coupon_can_used_by_cny"      => "优惠券只能使用人民币",
        "not_supported_delivery"      => "暂不支持该种托运方式",
        "order_amount_illegal"        => "订单金额非法",
        "can_not_buy_self_product"    => "不能购买自己店铺产品",
        "active_limit"                => "超过活动限购数量",
        "coupon_calculate_failed"     => "订单优惠券计算失败",
        "pay_failed"                  => "支付失败",
        "installment_not_support_app" => "分期付款不支持app，请在电脑端付款",
        "data_insert_failed"          => "数据插入失败，请重试",
        "params_illegal"              => "参数非法",
        "order_not_found"             => "订单不存在",
        "multi_order_not_support"     => "多店铺下单只支持非合同，非分批付款",
        "cancel_error_to_send"        => "请到APP上进行取消订单操作",
        "order_receive_freeze_error"  => "您已申请退款，不可以进行收货操作",
        "only_support_foreign_trad"   => "英文站只支持外汇交易",
        "only_support_USD"            => "英文站支持USD",
        "product_attr_error"          => "商品属性选择错误",
        "active_busy"                 => "宝贝太抢手啦，请稍后再试！",
        "address_empty"               => "地址不存在",
        "caller_too_many"             => "访问人数太多啦，请稍后再试！",
    ],
    "payment"                            => [
        "request_url_not_exists" => "该服务请求地址不存在",
        "notify_error"           => "支付回调异常",
    ],
    "request_fail"                       => "请求失败",
    "account"                            => [
        "create_failed"  => "创建失败",
        "update_failed"  => "更新失败",
        "destroy_failed" => "删除失败",
    ],
    "workorder"                          => [
        "process_status_error" => "已处理完成的不能再回复",
    ],
    "version"                            => [
        "version_get_failed" => "App 版本获取失败",
    ],
    "businessLicense"                    => [
        "repeat"         => "该商位已提交过电子营业执照申请",
        "created_failed" => "申请失败，稍后再试",
    ],
    "purchase"                           => [
        "generate_failed" => "采购单生成失败",
    ],
    "share"                              => [
        "expiration" => "分享已过期",
        "not_found"  => "分享不存在",
    ],
    "refund_order"                       => [
        "refund_not_exist"      => "售后单不存在",
        "order_not_exist"       => "订单不存在",
        "order_status_failed"   => "该订单状态不能退款",
        "order_contract_failed" => "只有非合同订单可以退款",
        "refund_exist"          => "不能重复申请退款",
        "without_paying"        => "分期付款时,未付尾款不能退款",
        "refund_limit"          => "退款金额不能超过可退金额",
        "apply_error"           => "申请退款失败",
        "without_shop_refuse"   => "商家未拒绝，不能修改申请",
        "cancel_status_failed"  => "当前状态不能撤销申请",
        "cancel_refund_failed"  => "撤销申请失败",
    ],
    "inquiry"                            => [
        "not_offer"         => "未报价不能删除",
        "product_not_found" => "产品记录不存在",
        "not_own_shop"      => "不能选择自己的店铺产品",
        "not_found"         => "询盘记录不存在",
    ],
    "logist"                             => [
        "product_not_exist"      => "产品不存在",
        "order_failed"           => "下单失败",
        "order_cannot_order"     => "订单已经存在物流订单，请取消物流订单后再试",
        "order_can_not_order"    => "当前订单存在收货方式不是买家自理的订单，不能发起物流订单",
        "data_failed"            => "数据获取失败",
        "illegal_data"           => "非法数据",
        "purchase_can_not_order" => "该采购单不能下单",
    ],
    "en"                                 => [
        "orders" => [
            "flag_errors"   => "flag 错误",
            "show_errors"   => "该链接不存在！",
            "price_errors"  => "无可购买价格",
            "out_of_stock"  => "暂无库存",
            "product_empty" => "产品为空",
        ],
    ],
    "kf"                                 => [
        "after_failed" => "投诉工单创建失败",
    ],
];
